# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /TSTRONG/src

# Copy package.json and package-lock.json to the working directory
COPY ./ ./

# Install dependencies
RUN npm install or npm i 

# Copy the rest of the application files
COPY . .

# Build the TypeScript application
RUN npm run build

# Expose the port your application runs on
EXPOSE 3000

# Define the command to run your application
CMD ["node", "src/server.ts"]
